Correct radioblog and homepage synopsis text + more
daveyshindig/radiOMG pull request #69
Opened 2018-04-19 09:58 UTC by dchan3

Require synopses in posts and update deprecated dependency

Revise synopsis render functions

2018-06-02 09:52 UTC, dchan3 commented
I shall see if the `moment-timezone` reinstallation and subsequent refactoring addresses #70.

2018-06-23 08:52 UTC, daveyshindig requested changes
Wow that was a lot of formatting changes. Thanks for all the enhancements and so on. I've requested a few changes. Check the comments.

2018-06-23 08:52 UTC, daveyshindig commented on client/main.css
> +  }
I can't accept this and line 2928. Nicki painstakingly created a type system, and using whatever font sizes outside of it breaks that. See lines 35-40 for acceptable sizes.

2018-06-23 08:52 UTC, daveyshindig commented on client/main.js
> +      this.docId);
Please remove console logging statements if they're not absolutely needed.

2018-06-23 08:52 UTC, daveyshindig commented on client/main.js
> +      if (Profiles.findOne({ userId: Meteor.userId() }).banned) {
Why the nested if statements here? It's a bad pattern. Preferably we'd join these with `&&`.

2018-06-23 08:52 UTC, daveyshindig commented on client/main.js
> +      if (Profiles.findOne({ userId: Meteor.userId() }).banned) {
Maybe there's a reason to do it this way but IDK

2018-06-23 08:52 UTC, daveyshindig commented on imports/ui/components/application/layout.html
> +      {{#if notice}}
I wish we could get rid of these too. Handlebars doesn't have an && huh.

2018-08-11 06:56 UTC, daveyshindig approved these changes

2018-08-11 08:59 UTC, merged